jump_platform:
    jump: 1.7
    dash: 1.7

speed_level: 7

respawn_points:
    respawn_1: { x: -4048, y: 84, z: -9428 }
    respawn_2: { x: -3956, y: 90, z: -9410 }
    respawn_3: { x: -3957, y: 96, z: -9329 }
    respawn_4: { x: -4051, y: 75, z: -9319 }
    respawn_5: { x: -3987, y: 96, z: -9360 }

respawn_height: 35
